version: '2.3'


services:
   asterisk:
     image: fgst/asterisk:base
     cap_add:
       - sys_ptrace                          # Only here to help testing
       - net_admin                           # Allow NFT, used by AutoBan
       - net_raw                             # Allow NFT, used by AutoBan
     environment:
       - SYSLOG_LEVEL=${SYSLOG_LEVEL-4}      # Logging
       - HOSTNAME=${TELE_SRV-tele}.${DOMAIN-docker.localhost}
       - PULSE_SERVER=unix:/run/pulse/socket # Use host audio
       - PULSE_COOKIE=/run/pulse/cookie      # Use host audio
       - WEBSMSD_PORT=${WEBSMSD_PORT-80}     # WEBSMSD internal port
     volumes:
       - tele_conf:/srv                      # Persistent storage
       - ./pulse:/run/pulse:rshared          # Use host audio
       - /etc/localtime:/etc/localtime:ro    # Use host timezone     
     deploy:
       mode: replicated
       replicas: 3
     networks:
       local:
         aliases:
           - asterisk.local
     
   
   kamailio_dispatcher:
     depends_on:
       - db
       - asterisk
     build:
      context: ${PWD}/kamailio
      dockerfile: Dockerfile
     ports:
       - "5060:5060/udp"
       - "5060:5060/tcp"
     restart: always
     networks:
       local:
         aliases:
           - kamailio_dispatcher.local

   db:
     image: mysql:5.7
     volumes:
       - /tmp/dbdata:/var/lib/mysql
       - ./containers/mysql/resources:/docker-entrypoint-initdb.d/
     ports:
       - "3306"
     environment:
       - MYSQL_ALLOW_EMPTY_PASSWORD=yes
       - MYSQL_USER=kamailio
       - MYSQL_PASSWORD=kamailiorw
       - MYSQL_DATABASE=kamailio
     healthcheck:
       test: mysql --user=root -e "select * from mysql.user"
       timeout: 45s
       retries: 5
     networks:
       local:
         aliases:
           - db.local

networks:
  local:
volumes:
  asterisk_conf:
  asterisk_spool:
  tele_conf:
