version: '3'


services:
   asterisk:
     image: andrius/asterisk:alpine_glibc-18.x
     volumes:
       - tele_conf_base:/etc/asterisk/            # Persistent storage
       - tele_spool_base:/var/spool/asterisk/
       - /etc/localtime:/etc/localtime:ro    # Use host timezone       
     ports:
     #  - "5061:5061/tcp"
     #  - "5062:5062/udp"
       - "10030-10039:10030-10039/udp"
     deploy:
       mode: replicated
       replicas: 1
     networks:
       local:
         aliases:
           - sip.oncx.cf


   asterisk1:
     image: fgst/asterisk:full
     cap_add:
       - sys_ptrace                          # Only here to help testing
       - net_admin                           # Allow NFT, used by AutoBan
       - net_raw                             # Allow NFT, used by AutoBan
     environment:
       - SYSLOG_LEVEL=${SYSLOG_LEVEL-4}      # Logging
       - HOSTNAME=${TELE_SRV-tele}.${DOMAIN-docker.localhost}
       - PULSE_SERVER=unix:/run/pulse/socket # Use host audio
       - PULSE_COOKIE=/run/pulse/cookie      # Use host audio
       - WEBSMSD_PORT=${WEBSMSD_PORT-80}     # WEBSMSD internal port
     volumes:
       - tele_conf1:/srv                      # Persistent storage
       - ./pulse1:/run/pulse:rshared          # Use host audio
       - /etc/localtime:/etc/localtime:ro    # Use host timezone     
     ports:
     #  - "5060:5060/udp"
       - "10000-10009:10000-10009/udp"
     deploy:
       mode: replicated
       replicas: 1
     networks:
       local:
         aliases:
           - cs1.oncx.cf

   asterisk2:
     image: fgst/asterisk:base
     cap_add:
       - sys_ptrace                          # Only here to help testing
       - net_admin                           # Allow NFT, used by AutoBan
       - net_raw                             # Allow NFT, used by AutoBan
     environment:
       - SYSLOG_LEVEL=${SYSLOG_LEVEL-4}      # Logging
       - HOSTNAME=${TELE_SRV-tele}.${DOMAIN-docker.localhost}
       - PULSE_SERVER=unix:/run/pulse/socket # Use host audio
       - PULSE_COOKIE=/run/pulse/cookie      # Use host audio
       - WEBSMSD_PORT=${WEBSMSD_PORT-80}     # WEBSMSD internal port
     volumes:
       - tele_conf2:/srv                      # Persistent storage
       - ./pulse2:/run/pulse:rshared          # Use host audio
       - /etc/localtime:/etc/localtime:ro    # Use host timezone     
     ports:
       - "10010-10019:10010-10019/udp"
     deploy:
       mode: replicated
       replicas: 1
     networks:
       local:
         aliases:
           - cs2.oncx.cf

   asterisk3:
     image: fgst/asterisk:base
     cap_add:
       - sys_ptrace                          # Only here to help testing
       - net_admin                           # Allow NFT, used by AutoBan
       - net_raw                             # Allow NFT, used by AutoBan
     environment:
       - SYSLOG_LEVEL=${SYSLOG_LEVEL-4}      # Logging
       - HOSTNAME=${TELE_SRV-tele}.${DOMAIN-docker.localhost}
       - PULSE_SERVER=unix:/run/pulse/socket # Use host audio
       - PULSE_COOKIE=/run/pulse/cookie      # Use host audio
       - WEBSMSD_PORT=${WEBSMSD_PORT-80}     # WEBSMSD internal port
     volumes:
       - tele_conf3:/srv                      # Persistent storage
       - ./pulse3:/run/pulse:rshared          # Use host audio
       - /etc/localtime:/etc/localtime:ro    # Use host timezone     
     ports:
       - "10020-10029:10020-10029/udp"
     deploy:
       mode: replicated
       replicas: 1
     networks:
       local:
         aliases:
           - cs3.oncx.cf
  
   
   kamailio_dispatcher:
     depends_on:
       - db
     build:
       context: ${PWD}/kamailio
       dockerfile: Dockerfile
     volumes:
       - dispatcher_conf_base:/etc/kamailio/
     environment:
       - PUBLIC_IP_ADDRESS=42.116.254.236
     ports:
     #   - "5080:5080/udp"
     #  - "5061:5061/udp"
        - "5060:5060/udp"
     #   - "5060:5060/tcp"
     #  - "10030-10039:10030-10039/udp"
     restart: always
     networks:
       local:
         aliases:
           - oncx.cf

   db:
     image: mysql:5.7
     volumes:
       - /tmp/dbdata:/var/lib/mysql
       - ./containers/mysql/resources:/docker-entrypoint-initdb.d/
     environment:
       - MYSQL_ALLOW_EMPTY_PASSWORD=yes
       - MYSQL_USER=kamailio
       - MYSQL_PASSWORD=kamailiorw
       - MYSQL_DATABASE=kamailio
     ports:
       - "3306"
     healthcheck:
       test: mysql --user=root -e "select * from mysql.user"
       timeout: 45s
       retries: 5
     networks:
       local:
         aliases:
           - db.local

networks:
  local:
volumes:
  dispatcher_conf_base:
  asterisk_conf:
  asterisk_spool:
  tele_conf_base:
  tele_spool_base:
  tele_conf1:
  tele_conf2:
  tele_conf3:
